### ISSUE TITLE
在 freecdn-manifest.txt 使用真实url

### ISSUE THREAD

**Issue by ceabq** [EtherDream/freecdn#16]
希望以种类似这种方式加载文件, 因为我图片是和主站分离的, 这样即使用户javascript没开,那么像 `<img src="url">` 还可以正常加载
```
https://cdn.jsdelivr.net/npm/typed.js@2.0.12/lib/typed.min.js
	https://ajax.cdnjs.com/ajax/libs/typed.js/2.0.12/typed.min.js
	https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.12/typed.min.js
	hash=UVQ5HtHTmtqBT3KY5cd4AvI47pp0gJwIM+q45HD9oLk=
```
但是目前好像只能以如下方式加载文件
```
/js/main.js
         https://example.com/test/a.js
         hash= ......
```

**Comment by lirko** [comment]
不在乎你使用什么访问方式，sw只拦截你设定的url，/js/main.js是相对路径自动会加上你当前的域名，也可以写文件的绝对路径，绝对路径可以和主站域名不一致

**Comment by ceabq** [comment]
我知道, 我的意思是在service worker不起动的情况下, /js/main.js 是无法加载的

**Comment by ceabq** [comment]
我希望以这种方式加载图片
```
https://main.example.com/test.jpg
         https://backup.example2.com/test.jpg
```
`<img src="https://main.example.com/test.jpg">`

**Comment by lirko** [comment]
https://github.com/EtherDream/freecdn/tree/master/examples/cdn-fallback
看文档的清单格式

**Comment by ceabq** [comment]
可以是可以的,就是要手写, withurl我也试过了,不行

**Comment by ceabq** [comment]
resolved,  由于cloudflare阻止了, freecdn拿不到正确的文件
顺带一提这样扫url的方式多少有点费流量
