### ISSUE TITLE
图床支持不太友好

### ISSUE THREAD

**Issue by yangchuansheng** [EtherDream/freecdn#3]
我看目前提供的方案都是将本地图片上传到 GitHub，然后使用公共 CDN 链接。如果我的博客中的图片已经使用了图床（例如 jsdelivr）该怎么办？该怎么实现自动选择？

**Comment by EtherDream** [comment]
要加速第三方 URL，可参考这个案例：https://github.com/EtherDream/freecdn/tree/master/examples/cdn-fallback

先把已有的外链的 URL 放在一个列表文件中，程序会搜索内容相同的其他 URL。

当然搜索前需要将其他 URL 导入到本地数据库，比如导入到 unpkg.com。可参考：https://github.com/EtherDream/freecdn/tree/master/examples/free-host

**Comment by xingpingcn** [comment]
https://github.com/xingpingcn/picture-bed-using-freecdn
写了个脚本处理这个问题
