### ISSUE TITLE
用户访问过启用了freecdn的网站后，能否在服务端主动停用

### ISSUE THREAD

**Issue by jsdtxm** [EtherDream/freecdn#4]
用户访问过启用了freecdn的网页后，即使在网页中移除了freecdn-loader.js的引用，依旧会使用freecdn的ServiceWorker来读取静态文件，是否有方法可以主动地在服务端停用客户端的freecdn？

**Comment by ceabq** [comment]
服务器发送no cache不知道会不会刷新

**Comment by EtherDream** [comment]
服务器实现的话，可以给网页响应头加个 Clear-Site-Data: "storage" 试试。

前端实现的话可以把 sw unregister 卸载掉。之后会考虑加个卸载的方法，通过配置清单文件卸载。

**Comment by jsdtxm** [comment]
@EtherDream 非常感谢您的回复，我使用了unregister直接卸载了全部sw，贴上代码供参考。

```js
navigator.serviceWorker.getRegistrations().then(function(registrations){
    for(let registration of registrations){
        registration.unregister();
    }
}); 
```
