### ISSUE TITLE
优先从本体链接加载?

### ISSUE THREAD

**Issue by ceabq** [EtherDream/freecdn#8]
如果有这样一个链接是这样配置的

https://www.example.com/original.png  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; https://www.example2.com/backup.png

有没有办法先从 https://www.example.com/original.png 加载
我试过 

https://www.example.com/original.png  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; https://www.example.com/original.png

但是最后变成无限循环

**Comment by EtherDream** [comment]
目前还不支持，下一个版本就可以了，可以在配置每个站点的权重。过几天我更新下。

**Comment by ceabq** [comment]
感谢，这个项目效果挺不错的，前端负载均衡确实节省了不少成本

**Comment by EtherDream** [comment]
我新增了站点权重的功能：https://github.com/EtherDream/freecdn/blob/master/docs/manifest/README.md#%E6%9D%83%E9%87%8D%E9%85%8D%E7%BD%AE

可以更新下 freecdn 试试。
